import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//creamos una clase para que manjene los metodos del arbol y segun el link que haga click se le pasa un metodo
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The TI but made in javascript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://docs.google.com/document/d/12h13tHDfVGYYaChX9QopWLC2VPsofp80GLLkwlGszg0/edit?usp=sharing">The TI #2!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing testing the AVLTree
        </p>

        <div className={styles.grid}>
          <a href="/inputTree" className={styles.card}>
            <h2>Test the AVLTree &rarr;</h2>
            <p>Try the implementation of an AVLTree using javascript</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
